spring:
  datasource:
    url: jdbc:h2:mem:user_db
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

